
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.json.JSONArray;
import org.json.JSONObject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Pratham Saroch
 */
public class Welcome extends javax.swing.JFrame {

    int check = 0;

    /**
     * Creates new form Welcome
     */
    public Welcome() {

        initComponents();
        setSize(1000, 650);
        setLocationRelativeTo(null);
        //METHOD-1 : Using Color Fields

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        topTrending();
        topUpcoming();
        
        getContentPane().setBackground(Color.BLACK);
        jPanel13.setVisible(false);
        jPanel14.setVisible(false);
        
        String photo = global.photo;
        String username = global.username;
        System.out.println("Username "+username);
        jButton10.setIcon(new ImageIcon(photo));
        jLabel13.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel13.setText(username);
        jProgressBar1.setVisible(false);
    }

    void topTrending() {

        for (int i = 1; i <= 5; i++) {

            String path = "src/myuploads/Trending" + i + ".jpg";
            try {
                BufferedImage bi = ImageIO.read(new File(path));

                bi = scale(bi, 160, 130);

                if (i == 1) {
                    jLabel3.setIcon(new ImageIcon(bi));
                } else if (i == 2) {
                    jLabel4.setIcon(new ImageIcon(bi));
                } else if (i == 3) {
                    jLabel5.setIcon(new ImageIcon(bi));
                } else if (i == 4) {
                    jLabel6.setIcon(new ImageIcon(bi));
                } else if (i == 5) {
                    jLabel7.setIcon(new ImageIcon(bi));
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }

    void topUpcoming() {

        for (int i = 1; i <= 5; i++) {

            String path = "src/myuploads/Upcoming" + i + ".jpg";
            try {
                BufferedImage bi = ImageIO.read(new File(path));

                bi = scale(bi, 180, 140);

                if (i == 1) {
                    jLabel8.setIcon(new ImageIcon(bi));
                } else if (i == 2) {
                    jLabel9.setIcon(new ImageIcon(bi));
                } else if (i == 3) {
                    jLabel10.setIcon(new ImageIcon(bi));
                } else if (i == 4) {
                    jLabel11.setIcon(new ImageIcon(bi));
                } else if (i == 5) {
                    jLabel12.setIcon(new ImageIcon(bi));
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    public static BufferedImage scale(BufferedImage src, int w, int h) {
        BufferedImage img
                = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        int x, y;
        int ww = src.getWidth();
        int hh = src.getHeight();
        int[] ys = new int[h];
        for (y = 0; y < h; y++) {
            ys[y] = y * hh / h;
        }
        for (x = 0; x < w; x++) {
            int newX = x * ww / w;
            for (y = 0; y < h; y++) {
                int col = src.getRGB(newX, ys[y]);
                img.setRGB(x, y, col);
            }
        }
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel14 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Top Trending");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 170, 170, 40);

        jButton1.setText("Explore");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 180, 80, 30);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jPanel3.setLayout(null);

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 160, 130);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 20, 160, 130);

        jPanel4.setLayout(null);

        jLabel4.setText("jLabel4");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 160, 130);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(210, 20, 160, 130);

        jPanel5.setLayout(null);

        jLabel5.setText("jLabel5");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 0, 160, 130);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(400, 20, 160, 130);

        jPanel6.setLayout(null);

        jLabel6.setText("jLabel6");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 160, 130);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(590, 20, 160, 130);

        jPanel7.setLayout(null);

        jLabel7.setText("jLabel7");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(0, 0, 160, 130);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(780, 20, 160, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 210, 950, 170);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Top Upcomming");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 390, 200, 40);

        jButton2.setText("Explore");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 400, 80, 30);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel9.setLayout(null);

        jLabel8.setText("jLabel8");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(0, 0, 160, 130);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(20, 20, 160, 130);

        jPanel10.setLayout(null);

        jLabel9.setText("jLabel9");
        jPanel10.add(jLabel9);
        jLabel9.setBounds(0, 0, 160, 130);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(210, 20, 160, 130);

        jPanel8.setLayout(null);

        jLabel10.setText("jLabel10");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(0, 0, 160, 130);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(400, 20, 160, 130);

        jPanel11.setLayout(null);

        jLabel11.setText("jLabel11");
        jPanel11.add(jLabel11);
        jLabel11.setBounds(0, 0, 160, 130);

        jPanel2.add(jPanel11);
        jPanel11.setBounds(590, 20, 160, 130);

        jPanel12.setLayout(null);

        jLabel12.setText("jLabel12");
        jPanel12.add(jLabel12);
        jLabel12.setBounds(0, 0, 160, 130);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(780, 20, 160, 130);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 430, 950, 170);

        jButton3.setText("Settings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(890, 20, 75, 30);

        jButton4.setText("More");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 10, 80, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 20, 320, 40);

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(640, 30, 90, 23);

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(null);

        jButton6.setText("Movie");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton6);
        jButton6.setBounds(20, 20, 90, 23);

        jButton7.setText("Actor");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7);
        jButton7.setBounds(20, 50, 90, 23);

        jButton8.setText("TV Show");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton8);
        jButton8.setBounds(20, 80, 90, 23);

        jButton9.setText("Movie House");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton9);
        jButton9.setBounds(10, 110, 110, 23);

        getContentPane().add(jPanel13);
        jPanel13.setBounds(120, 10, 130, 140);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(330, 80, 230, 20);

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setLayout(null);

        jButton10.setText("Login First");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton10);
        jButton10.setBounds(20, 10, 120, 80);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("name");
        jPanel14.add(jLabel13);
        jLabel13.setBounds(20, 100, 120, 20);

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton11);
        jButton11.setBounds(150, 10, 50, 23);

        getContentPane().add(jPanel14);
        jPanel14.setBounds(770, 10, 210, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        UpcomingMovies obj = new UpcomingMovies();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
//        for (int i = 0; i < 100; i++) {
//            System.out.println(i);
//            jProgressBar1.setValue(i);
//            jProgressBar1.setString(i + "%");
//            try {
//                Thread.sleep(100);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
        
        TopTrending obj = new TopTrending();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    int flag = 0;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (check == 0) {
            System.out.println("Inside TRUE");
            jPanel13.setVisible(true);
            flag = 1;
        }

        if (check == 1) {
            System.out.println("Inside FALSE");
            jPanel13.setVisible(false);
            flag = 0;
        }

        if (flag == 1) {
            check = 1;
        }

        if (flag == 0) {
            check = 0;
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        SearchActor obj = new SearchActor("Search Movie");
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        SearchActor obj = new SearchActor("Search Actor");
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        SearchActor obj = new SearchActor("Search TV Show");
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        SearchActor obj = new SearchActor("Search Movie House");
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel14.setVisible(true);
        jButton3.setVisible(false);
        
        jButton10.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        });
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jPanel14.setVisible(false);
        jButton3.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        UserProfile obj =  new UserProfile();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String search = jTextField1.getText();
        search = search.replace(" ", "%20");

        SearchActor obj = new SearchActor(search);
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    void renderFun(String search){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private static class IconImpl implements Icon {

        public IconImpl() {
        }

        @Override
        public void paintIcon(Component c, Graphics g, int x, int y) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public int getIconWidth() {
            return 160;
        }

        @Override
        public int getIconHeight() {
            return 130;
        }
    }
}
